### ISSUE TITLE
User Store 9.1-Unable to set the role for a member after accepting the applicant

### ISSUE THREAD

**Issue by adorapham** [FightPandemics/FightPandemics#2398]
Unable to set the role for a member after accepting the applicant.
please see the record on , near the end starting from 1:30 
https://app.slack.com/client/T010BHVS3EF/C010BHVT1MZ/files/F022X4NME85

**Comment by xJamesScott** [comment]
@adorapham Bug fix released

**Comment by hiran11** [comment]
@ChunPingYang @xJamesScott   Looks like the issue is not fixed . 
1) As an individual user even after  i join the Org "Join Us" CTA button is not disabled .
2) Even when my application as an individual has been accepted "Join Us " CTA button is kept enabled. The individual name is listed as member in Members Tab. 
3)   As a owner of the account , unable to set the role permission. 
4) The static data is populated in the Role description for Wiki editor and Administrator. 

https://user-images.githubusercontent.com/51660881/120036342-01d77e00-bfce-11eb-88e5-8639e007f2f9.mp4


https://user-images.githubusercontent.com/51660881/120036352-04d26e80-bfce-11eb-946f-2ca737365fdf.mp4


https://user-images.githubusercontent.com/51660881/120036373-0c921300-bfce-11eb-8856-7310b676ecfc.mp4


https://user-images.githubusercontent.com/51660881/120036393-1287f400-bfce-11eb-9b03-2fa09c872adb.mp4
