### ISSUE TITLE
Incorrect redirection to login when the user wants to see the feed

### ISSUE THREAD

**Issue by ppagarawal** [FightPandemics/FightPandemics#685]
The user is being redirected to the sign in page when he should be redirected to the feed only. He must not necessarily be signed in for that. 

The redirection to the sign in page should not happen

Flow:
![bug](https://user-images.githubusercontent.com/6276256/84406166-c7db6380-ac26-11ea-8b7c-2140a0d71073.gif)

**Comment by omarzoghayyer** [comment]
@ppagarawal I think it has been already fixed on other branch. I just tried it and it redirect to feed page. 

<img width="518" alt="Screen Shot 2020-06-11 at 5 08 03 PM" src="https://user-images.githubusercontent.com/49251966/84450789-1debdf00-ac06-11ea-99d0-e7986fc74808.png">

**Comment by idjevm** [comment]
@ppagarawal I think here actually we should still continue to step three which gives the option to the user to give the email and for us to capture their email. Having it jump from step 2 to the feed would skip that extra step. Either way, on step 3, the user would have the option to skip inputting their email so I think from here you should move to step 3 @omarzoghayyer. Let's wait to see what @ppagarawal says.

**Comment by ppagarawal** [comment]
@idjevm @omarzoghayyer
I understand your point. However, the next button available also enables the user to go to step 3/3. I think that it is fine to have it redirect to feed for now.

**Comment by pthoma14** [comment]
@ppagarawal Indira, Vik, and I just ran the test and we believe it's working Prateek.

**Comment by omarzoghayyer** [comment]
@pthoma14  Thank you for testing it. 
We will close this issue for now, and we will reopen it if needed.
