### ISSUE TITLE
Confirmation for delete a post is Not getting displayed ,while deleting a post from Feed

### ISSUE THREAD

**Issue by sheeba1** [FightPandemics/FightPandemics#929]
Steps
1.Login to https://staging.fightpandemics.work/
2.Go to Feed and a Create a Post as Individual.
3.Go back to Feed where posts are displayed
4.Click on ellipsis and select delete. 
Result: Post is deleted without asking for confirmation. 
Expected: A confirmation dialog box should be displayed as shown below:

![image](https://user-images.githubusercontent.com/65972693/86183618-48cfa180-bae7-11ea-8e81-7145dfc478ed.png)

**Comment by silenceway** [comment]
Fixed in: https://github.com/FightPandemics/FightPandemics/pull/960

**Comment by idjevm** [comment]
Reopening this as it is not resolved yet but will be resolved once PR #960 gets merged. Reopening so people avoid creating a new issue with this since the feature is not in staging yet.

**Comment by sheeba1** [comment]
@silenceway  @idjevm  This is Not resolved  for posts from Feed ->Posts.

**Comment by silenceway** [comment]
Changes are done, PR wasn't merged yet. It contains the fix for the feed page. It was added with comments changes because we need to update the current flow. You can see some of the changes in client/src/pages/Feed.js file.

**Comment by idjevm** [comment]
Yeah that's true, changes are not on staging yet but the PR is ready. @silenceway is the PR ready to be merged?

**Comment by sheeba1** [comment]
@silenceway  @idjevm  wanted to check with you if this fix is good for mobile too?

**Comment by sheeba1** [comment]
@silenceway  @idjevm added Mobile tag too. Let me know if I need to create another defect Thanks!
